Laravel-Backpack/Generators

src/Console/Commands/CrudRequestBackpackCommand.php
Remove slash in  description command
=> Remove backslash in command description

src/Console/stubs/crud-controller.stub
Change of double quotes to single quotes in the method setModel() in the generator. Since the model name is specified with a namespace (which contain a backslash), this is recognized by many editors as escaping (for example PhpStorm). Using single quotes allows you to get rid of this.
=> Getting rid of the escaping in the model name

src/Console/stubs/crud-controller.stub
We should not hardcode `admin` prefix here, we should use the one specified in config by default.
=> Controller stub should respect the admin prefix from config

src/Console/Commands/CrudControllerBackpackCommand.php
This should solve issues with resources such as "category" (which is currently expanded to "categorys") in CRUD Controller's setUp() method built from stub.
=> Using str_plural() instead of appending s

src/Console/Commands/CrudModelBackpackCommand.php, src/Console/Commands/ModelBackpackCommand.php
When running an artisan command to generate a model, we sometimes get a wrong plural name for the table, for example:
```php artisan backpack:crud-model currency```
Will result with:
```protected $table = 'currencys';```
We now use Laravel's pluralizer instead.
=> Fix generated table names for models

src/Console/stubs/crud-controller.stub
The annotation now allows IDE's to autocomplete the code when referencing `$crud`.
=> Added annotations to the base crud controller stub

src/Console/stubs/model.stub
for some reason with this space I wasn't able to align `public $timestamps = false;` under `protected $primaryKey = 'id';` correctly
=> removed unnecessary space from model.stub

src/Console/stubs/crud-controller.stub
Query should have just one "=" and not 2 of it
=> Fix Advanced Queries Example

src/Console/stubs/crud-request.stub
this is a break changing commit ( if user uses old Base version this will cause problems  ) 
i would like to use \Auth::guard('admin')->check(); but they may uses another guard name for an admin panel.
=> use backpack_auth() function from 0.9.x updates

src/Console/stubs/crud-controller.stub
Since we now use AJAX tables by default there is no need to have the `$this->crud->enableAjaxTable()` within the stub. Caused some confusion on gitter.
=> Remove Ajax as commented documentation in controller stub

src/Console/stubs/crud-controller.stub
- Explicitly mention people shouldn't use ```setFromDb()```, with standard TODO.
- Remove commented API methods.
=> Simplified crud controller stub

composer.json, src/Console/Commands/ChartBackpackCommand.php, src/Console/Commands/ChartControllerBackpackCommand.php, src/Console/Commands/CrudBackpackCommand.php, src/Console/Commands/CrudOperationBackpackCommand.php, src/Console/stubs/chart-controller.stub, src/GeneratorsServiceProvider.php
- Adds commands needed by https://github.com/Laravel-Backpack/CRUD/pull/2596:
- ```php artisan backpack:chart InactiveUsers``` - generates chart controller and route
- ```php artisan backpack:chart-controller InactiveUsers``` - generates just chart controller
- removes some more Laravel string helpers (leftovers)
- provides support for Backpack 4.1
=> Support for Backpack 4.1

src/Console/Commands/CrudModelBackpackCommand.php
When `App\Models\Article.php` exists, but does NOT have CrudTrait, this PR makes sure that when you run `php artisan backpack:crud article` the CrudTrait is added to the model. 
This makes it possible to:
- easily use existing models - just generate admin panels for them;
- easily generate the models with whatever tool you want (laracasts, blueprint, whatever) - just generate admin panels for them;
Non-breaking change in my opinion.
=> add CrudTrait to models that exist, but don't have it

src/Console/Commands/BuildBackpackCommand.php, src/GeneratorsServiceProvider.php
Fixes #76
Adds a `php artisan backpack:build` command, that goes through the App folder and looks at all the models that exist, then calls `php artisan backpack:crud` on each one of them.
Not sure it's general enough - it might currently work only inside the `Models` folder, and only for models who _directly_ extend the Eloquent model. But... it works!!
I'm open to feedback and improvements.
---
Rephrased, what this PR does is that it allows a different way of building Laravel apps with admin panels. You can build your entire front-end, in the process of course you'd be creating models. Then at the end, when you're done with the front-end, you can just install Backpack and run the `build` command, and it will generate admin panels for all models.
=> Adds backpack:build command to generate CRUDs for all models

CHANGELOG.md, src/Console/Commands/CrudControllerBackpackCommand.php, src/Console/stubs/crud-controller.stub
This PR replaces the `setFromDb()` statements in the CrudController stub with actual columns or fields. When someone generates a CrudController, here's how what they're getting is different:
```diff
protected function setupListOperation()
{
-        $this->crud->setFromDb();
+        CRUD::column('category_id');
+        CRUD::column('title');
+        CRUD::column('slug');
+        CRUD::column('content');
+        CRUD::column('image');
+        CRUD::column('status');
+        CRUD::column('date');
+        CRUD::column('featured');
+        CRUD::column('deleted_at');
+        CRUD::column('created_at');
+        CRUD::column('updated_at');
}
protected function setupCreateOperation()
{
$this->crud->setValidation(ArticleRequest::class);
-        $this->crud->setFromDb();
+ …
```
=> Generate crud controllers with explicit fields and columns, not setFromDb

src/Console/Commands/CrudModelBackpackCommand.php
See #98 for details. But in short using PHP_EOL has inconsistent results on Windows, and this PR tries to fix that by using regex instead.
=> fix #98 - adding CrudTrait to Model generates error on Windows OS

src/Console/Commands/BuildBackpackCommand.php, src/Console/Commands/ChartBackpackCommand.php, src/Console/Commands/ConfigBackpackCommand.php, src/Console/Commands/CrudBackpackCommand.php, src/Console/Commands/CrudModelBackpackCommand.php, src/Console/Commands/ViewBackpackCommand.php
Fix for #97.
This PR validates Models on `\App\` namespace and `\App\Models\` namespace.
If both exists user is prompt to select wish one to use.
I had to move all `Artisan::call()` to `$this->call()` to be able to use prompts.
```
Controller already exists!
Multiple models with this name were found, which one do you want to use?:
[1] Use App\Test
[2] Use App\Models\Test
> 1
1
Model already uses CrudTrait.
Request already exists!
Route already exists!
Sidebar item already exists!
```
Also, by using `$this->call()` messages are properly highlighted.
=> Proper validation for models on app or models namespace

src/Console/Commands/CrudControllerBackpackCommand.php
This PR fixes the problem reported here; https://github.com/Laravel-Backpack/Generators/issues/95#issuecomment-665967884 and confirmed by @tabacitu here; https://github.com/Laravel-Backpack/Generators/issues/95#issuecomment-760959721
The problem was;
```php
if (! count($model->getFillable())) {
$attributes = $model->getFillable();
```
That is inverted, so, if there is fillable, we use it.
Refactored `replaceSetFromDb` a little bit along the way.
=> Fixed wrong condition causing fields and columns to not be filled

src/Console/Commands/CrudBackpackCommand.php, src/Console/Commands/CrudControllerBackpackCommand.php, src/Console/stubs/crud-controller.stub
Until now doing something like;
`php artisan backpack:crud ...`
`product_category` renders `Route::crud('product_category', 'Product_categoryCrudController');`
`product-category` renders `Route::crud('product-category', 'Product-categoryCrudController');`
`productCategory` renders `Route::crud('productcategory', 'ProductCategoryCrudController');`
Also, the controller entity names were wrong.
```CRUD::setEntityNameStrings('productcategory', 'product_categories');```
--- 
This PR allows devs to use any format, either kebab-case, snake_case or Title Case.
`php artisan backpack:crud ...`
`product_category`, `product-category`, `productCategory`
It will always render what is expected.
`routes/custom.php`
```php
Route::crud('product-category', 'ProductCategoryCrudController');
``` …
=> Fix for multiple word crud command

src/Console/Commands/CrudBackpackCommand.php
fixes: #125
The generated sidebar item would be:
`<li class='nav-item'><a class='nav-link' href='{{ backpack_url('page') }}'><i class='nav-icon la la-question'></i> Pages</a></li>`
The generated sidebar item becomes:
`<li class="nav-item"><a class="nav-link" href="{{ backpack_url('page') }}"><i class="nav-icon la la-question"></i> Pages</a></li>`
Use escaped double string instead of single quotes that would become nested when echoing the blade syntax.
I don't think it's a breaking one.
??
=> use escaped double-slash to avoid inner single slash

src/Console/Commands/PageBackpackCommand.php, src/Console/Commands/PageControllerBackpackCommand.php, src/Console/stubs/page-controller.stub, src/Console/stubs/page.stub, src/GeneratorsServiceProvider.php
Fixes #138.
Developers can run;
```cmd
php artisan backpack:page status
```
```cmd
php artisan backpack:page portugal --view-path=status --layout=blank
```
This will also work (thanks to @pxpm suggestion);
```cmd
php artisan backpack:page status.romania
```
`--view-path` defaults to `admin`, but devs are free to change it.
`--layout` also defaults to `blank`.
Later we may add `--controller-path`.
=> Command to create a new page

src/Console/Commands/CrudControllerBackpackCommand.php, src/Console/Commands/CrudModelBackpackCommand.php, src/Console/Commands/CrudRequestBackpackCommand.php
Fixes https://github.com/Laravel-Backpack/Generators/issues/139.
Message for the generated Model, Controller and Request was using the namespace instead of the file link.
All generated files are now with relative paths;
No 👌
Run `php artisan backpack:crud user`.
=> Converted namespaces into file links on backpack:crud command

README.md, src/Console/Commands/ButtonBackpackCommand.php, src/Console/stubs/button.stub, src/GeneratorsServiceProvider.php
New Feature:
What I did:
Created an operation, had no way to create a custom button really quick (with a stub).
What happens:
Run php artisan backpack:button email and it would create the button for me.
=> Create a php artisan backpack:button command

src/Console/Commands/BuildBackpackCommand.php
Since `backpack:crud` now asks for the request type, and `backpack:build` runs dozens of times that command, it is asking the user to input that each time.
This will default the variable to `request`, but also allows adding the variable as an arg of the command.
```php
php artisan backpack:build --validation=field
```
---
I though about adding the question here too, but I don't know if it makes sense, I think this is enough 🤷‍♂️
Let me know @tabacitu 🙌
=> Default validation as request for the backpack:crud command

src/Console/Commands/CrudControllerBackpackCommand.php
Fixes https://github.com/Laravel-Backpack/Generators/issues/131.
@tabacitu In my case the fields/columns are ordered accordingly to the database.
Can you test on your side? Because I haven't done nothing to fix it, it may be an issue on your side onyl.
If it is, we are reading the values from DB with `Schema::getColumnListing`.
I saw some doing `DB::select("SELECT column_name FROM information_schema.columns WHERE table_name = 'table_name' ORDER BY ordinal_position")`.
Let me know 1st if you still have the issue, (and if so) 2nd if you think we should change to that approach above 👌
=> Fixed CRUD Controller generated fields and columns

src/Console/Commands/CrudModelBackpackCommand.php, src/Console/Commands/PageControllerBackpackCommand.php
Reported here, stackoverflow etc. 
Str::lcfirst() is not available at L9. 
we use the native PHP function.
nop
try building a CRUD in L8 project.
=> remove l8 breaking code

src/Console/Commands/CrudOperationBackpackCommand.php, src/Console/stubs/crud-operation.stub
This PR is poiting to https://github.com/Laravel-Backpack/Generators/pull/133 from @pxpm.
This extends the changes on `crud-operation` command.
Generated operations are now more similar with the default CRUD operations.
Here is a sample output;
```php
<?php
namespace App\Http\Controllers\Admin\Operations;
use Illuminate\Support\Facades\Route;
trait TestingNameOperation
{
/**
* Define which routes are needed for this operation.
*
* @param string $segment    Name of the current entity (singular). Used as first URL segment.
* @param string $routeName  Prefix of the route name.
* @param string $controller Name of the current CrudController.
*/
protected function setupTestingNameRoutes($segment, $routeName, $controller)
{
Route::get($segment.'/testing-name', [
'as'        => …
```
=> use the camelcased version of operation name - extended

src/Console/Commands/CrudOperationBackpackCommand.php, src/Console/stubs/crud-operation.stub
An operation with name `BrowserPrint` would become `browserprint` as operation name in stub. I think it's unexpected, we should keep using the `BrowserPrint` name, since it's the name developer gave to the operation when creating it in console.
=> use the camelcased version of operation name

src/Console/Commands/ColumnBackpackCommand.php, src/Console/stubs/column.stub, src/GeneratorsServiceProvider.php
It's Handy
Genrate columns using command line.
`php artisan backpack:column {name}`
`php artisan backpack:column {name} --from={column}`
=> Artisan command to generate new columns

src/Console/Commands/ButtonBackpackCommand.php, src/Console/Commands/ColumnBackpackCommand.php, src/Console/Commands/FieldBackpackCommand.php, src/Console/Commands/FilterBackpackCommand.php, src/Console/Commands/WidgetBackpackCommand.php, src/Console/stubs/field.stub
This PR includes a bunch of fixes to;
- `src/Console/Commands/ButtonBackpackCommand.php`
- `src/Console/Commands/ColumnBackpackCommand.php`
- `src/Console/Commands/FieldBackpackCommand.php`
- `src/Console/Commands/FilterBackpackCommand.php`
- `src/Console/Commands/WidgetBackpackCommand.php`
Mostly opinionated, but some bug fixes too;
- Fixed order of messages on the console.
- `getNameInput` is now on all classes to make sure the name is always in the desired format.
This also aims to "standardize" these classes, in near future they may all be optimized by moving common methods to a trait.
=> Fixes on create/publish views commands

src/Console/Commands/ButtonBackpackCommand.php, src/Console/Commands/ColumnBackpackCommand.php, src/Console/Commands/FieldBackpackCommand.php, src/Console/Commands/FilterBackpackCommand.php, src/Console/Commands/WidgetBackpackCommand.php
This allows to not pass the name when using `--from`.
When using from the name was being always required;
```zsh
php artisan backpack:filter bulk_clone --from bulk_clone
```
Now, if it is not given, it will get it from the `--from` option, allowing to simplify the command;
```zsh
php artisan backpack:filter --from bulk_clone
```
=> Get the "name" from "--from" when it's not given

src/Console/Commands/Views/PublishOrCreateViewBackpackCommand.php
I use symlinks in my demo project, and I found that files outside of the project (demo) scope, were not being published, because they were being prefixed with the project `base_path()`.
By using PHP native [`realpath`](https://www.php.net/manual/en/function.realpath.php) method, all paths are now allowed 🙌
This will transform all paths in absolute paths, symlinks are properly resolved, it also resolves references `\..\` and extra slashes.
_**Note**: This still allows relative paths._
This should have been done this way the first time, my bad ✋
No.
=> Allow absolute paths outside of app scope

src/Console/Commands/Views/PublishOrCreateViewBackpackCommand.php
This should fix situations where a relative path is provided but it is interpreted as an absolute file path in unix like file systems because of the leading slash `/`.
`/path/to/something` is interpreted as relative to unix root, whereas it ~should~ **may**_(a)_ be a relative to the working dir `path/to/something`
This PR aims to make Generators support both, by looking for both.
---
_(a)_ Path can be both, either relative or absolute, that's why we can't just remove the slash `/`.
=> Fix for absolute paths in Unix file systems

src/Console/Commands/Views/WidgetBackpackCommand.php
Widget have a different path than the other views. This PR adds an override of the `getPath()` only to the widget command.
=> Override widget command path

src/Console/Commands/CrudBackpackCommand.php
When you generated a CRUD, the default icon was a question mark, to force devs into choosing their own. When you generated a Page, the default icon was STILL a question mark... so... you couldn't really differentiate between what you've created.
When a new CRUD is created, the default icon is a table, instead of a question mark:
---
Anyone please double-check, so I can merge?
=> change default menu icon for generated CRUDs

src/Console/Commands/BuildBackpackCommand.php
Fixes https://github.com/Laravel-Backpack/Generators/issues/120.
`backpack:crud` was generating CRUDs for abstract models, and it was also skipping valid models that simply don't extend **directly** `Illuminate\Database\Eloquent\Model`.
- First it tries to guess the namespace by the file path
- Then it also tries to find the namespace by the file contents.
No.
- Having an abstract Model on Models folder (should **not** generate CRUD)
- Having a model that extends another Model or an abstract Model (**should** generate CRUD)
@tabacitu I think I'll ask @pxpm to take a quick look at this one, he is aware of this kind of stuff, requiring files on runtime, guessing namespaces ... he may find something that I should not have done 😅
=> [BugFix] avoid backpack:build to generate interfaces for abstract models and others

src/Console/Commands/ModelBackpackCommand.php
With new backpack versions using newer Laravel version and they have the different location should be adjusted to that. Perhaps could add in an option to use the old location but Backpack:Crud-Model puts it in the 'App\Models' folder.
Location for new models was simply `App` instead of the new `App\Models` location. `Backpack:Crud-Model` uses the correct location.
Corrected location for when models are generated.
Simply adjusted the path for the namespace.
Depends on the version of Laravel being used anything older then 8 it may be.
Adjust the namespace.
=> Fix location for where model is generated

composer.json
Backpack uses Laravel 8 as a minimum requirement and Laravel 8 has a minimum requirement of PHP 7.3.
Issue https://github.com/Laravel-Backpack/community-forum/issues/399 describes a logic that fails because of arrow function used in the code. Arrow functions are introduced in PHP 7.4 and therefore fail in PHP 7.3.
After setting the minimum PHP version to 7.4 the issue is resolved, as the user is forced to use PHP version 7.4 instead of 7.3.
Added `"php": "^7.4|^8.0"` as `required` in `composer.json`.
It could be a breaking change for 0.7% of the users that use PHP 7.3 (according to the stats provided by Pedro in the linked issue)/
1. Do a fresh installation of latest Backpack version under PHP 7.3 - artisan will fail after the installation
2. Do a fresh installation of latest Backpack …
=> Added PHP 7.4 as a min. version requirement

src/Console/Commands/PageBackpackCommand.php
We were getting a deprecation warning message:
`PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /app/vendor/backpack/generators/src/Console/Commands/PageBackpackCommand.php on line 73`
Stop getting the warning message.
N/A
Non-breaking
N/A
=> Fix deprecation warning message

src/Console/Commands/CrudModelBackpackCommand.php
fixes #181 
This is the same script snippet used in devtools `Add Crud Trait` button. 
We should probably extract this bit of code to some place where it could be re-used by both devtools button and generators command. 
For now they have the same code 👍
=> fix add crudtrait to crud

src/Console/Commands/BuildBackpackCommand.php
This StackOverflow post - https://stackoverflow.com/questions/75451809/artisan-backpackbuild-fails-with-badmethodcallexception - shows we have a bug in the current Generators + L8.
That's because `Stringable::value()` [was added in Laravel 9](https://github.com/laravel/framework/commit/d7cf744ca1601c27410dd6b8b4d1cb7389bd3039), not L8. 
We're still using the string, but without the method.
The old switcheroo.
Non-breaking.
Run `php artisan backpack:build` with the setup defined here  - https://stackoverflow.com/questions/75451809/artisan-backpackbuild-fails-with-badmethodcallexception
=> Fix: `build` command triggered an error on Laravel 8

src/Console/Commands/CrudModelBackpackCommand.php
Last fix I did relied on the first class `;`. 
That would broke in case developer used `declare(strict_types=1);` at the top of the file.
It does not break anymore.
Use the `namespace` definition as the placeholder to add the crud trait.
No
=> Use class namespace when adding CrudTrait to model

src/Console/Commands/PageBackpackCommand.php
Fixes #178
Deprecation warning, see #178
No deprecation warning
Used `{$filePath}` instead of `${filePath}`
Non-breaking
Test it in PHP 8.2
=> Fix deprecation warning

src/Console/Commands/CrudBackpackCommand.php, src/Console/Commands/PageBackpackCommand.php
We were generating simple HTML for menu items, even though we added blade components for them in https://github.com/Laravel-Backpack/CRUD/pull/5135/
We generate menu items using the Blade components.
=> When generating cruds use blade components for menu items

src/Console/Commands/BuildBackpackCommand.php
We already remove some calls to Str::value() as it's not available in Laravel 8. https://github.com/Laravel-Backpack/Generators/pull/185
This ones were leftovers. https://github.com/Laravel-Backpack/Generators/issues/196
We no longer use the `Str::value()` function in v3 of generators.
=> dont use Str value() function unavailable in Laravel 8

src/Console/stubs/crud-controller.stub, src/Console/stubs/crud-model.stub, src/Console/stubs/field.stub, src/Console/stubs/filter.stub, src/Console/stubs/model-softdelete.stub, src/Console/stubs/model.stub
This is mainly to fix https://github.com/Laravel-Backpack/Generators/issues/193 removing the mention to array syntax
I also removed the `$dates` property from the model, it had been deprecated some time ago https://github.com/laravel/framework/pull/42587
Updated the field stub to use the basset directives ... and stopped or this PR would blow out of scope.
=> update stubs - remove $dates property, use basset, remove array syntax

src/Console/Commands/ChartControllerBackpackCommand.php, src/Console/Commands/ConfigBackpackCommand.php, src/Console/Commands/CrudControllerBackpackCommand.php, src/Console/Commands/CrudModelBackpackCommand.php, src/Console/Commands/CrudOperationBackpackCommand.php, src/Console/Commands/CrudRequestBackpackCommand.php, src/Console/Commands/ModelBackpackCommand.php, src/Console/Commands/PageBackpackCommand.php, src/Console/Commands/PageControllerBackpackCommand.php, src/Console/Commands/RequestBackpackCommand.php, src/Console/Commands/Traits/PublishableStubTrait.php, src/Console/Commands/ViewBackpackCommand.php, src/Console/Commands/Views/PublishOrCreateViewBackpackCommand.php, src/GeneratorsServiceProvider.php
As started in https://github.com/Laravel-Backpack/Generators/pull/188 we didn't allow to publish the stubs.
I picked up the code from that PR a took it to the final stage.
You can now publish the stubs with `php artisan vendor:publish --tag=backpack-generators-stubs` and the commands will pick either the stub from the user folder, or use the one in the package. 
Shadownbane did almost all the work, all credits goes to him. We added a trait that return the stub path for components. 
No I don't think so.
=> Pr/188 - allow stub publish

src/Console/Commands/CrudControllerBackpackCommand.php
Trying to create a CrudController with `php artisan backpack:crud Something` and choosing the `fields` has the validation source, the command would fail to remove the `setValidation` from the final class, and that would raise errors since the RequestClass is not created when `fields` is chose. 
It works 🤷‍♂️
=> fix controller generation when field is used as validation source

src/Console/Commands/CrudFormOperationBackpackCommand.php, src/Console/stubs/crud-form-operation.stub
I have the need to quickly generate forms that are not using id in routes. 
Even if the "required change" is to make `routesHaveIdSegment: false`, the generated Operation had alot of `$id` references when not needed, so they needed to manually cleaned.
One can use `--no-id` to generate a form without $id parameter. 
The generated operation files will now on use named parameters on the `formAction` callback. 
This will also help in the fact that we need to do a breaking change in https://github.com/Laravel-Backpack/CRUD/pull/5459 and people generating operations with the commands after this PR will not be affected.
=> add option to generate forms without id, use named parameters in formAction

src/Console/stubs/page.stub
reported by a genius here: https://github.com/Laravel-Backpack/DevTools/issues/350
The page stub was fairly basic, and wasn't consistent in all themes/layouts. Additionally developers would have quite a hard time to replicate our pages with the headers and the container. 
I think it's easier to just remove what you don't need, than trying to figure out how to add this stuff.
Changed the stub file.
Non. If developers had the stub published, their custom stub still takes precedence.
=> Update page stub to closely match backpack pages
